version: 2.1 # https://circleci.com/docs/2.0/configuration-reference
jobs:
  build:
    resource_class: small
    working_directory: /go/src
    docker:
      - image: circleci/golang:1.16 # https://hub.docker.com/r/circleci/golang/ , https://hub.docker.com/_/golang?tab=description
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            go test -v ./...
      - run:
          name: Run code coverage
          command: |
            pwd
            mkdir -p /tmp/test-results/test2json/
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/test-results
            go test -v ./... | go tool test2json > /tmp/test-results/test2json/test-output.json
            gotestsum --junitfile /tmp/test-results/gotestsum-report.xml -- stringsmoar

      - store_artifacts: # Upload test summary for display https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # Upload test results for display https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results

