version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/go:1.24 # https://circleci.com/developer/images/image/cimg/go
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...
      - run:
          name: Run code coverage
          command: |
            mkdir -p /tmp/test-results
            go test -coverprofile=c.out
            go tool cover -html=c.out -o /tmp/test-results/coverage.html
      - store_artifacts:
          path: /tmp/test-results
          destination: test-output
